plugins {
    id 'java-library'
}

dependencies {
    api project(':ui-annotations')
    api project(':ui-state')
    api project(':ui-layout')
    api project(':ui-runtime')
    api project(':ui-foundation')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.25.3'
}

test {
    useJUnitPlatform()
}
