rootProject.name = 'JavaUI'

include ':ui-annotations'
include ':ui-state'
include ':ui-runtime'
include ':ui-layout'
include ':ui-renderer'
include ':ui-input'
include ':ui-animation'
include ':ui-foundation'
include ':ui-material'
include ':ui-navigation'
include ':ui-interop'
include ':ui-compiler'
include ':ui-gradle-plugin'
include ':ui-lint'
include ':ui-android-studio-plugin'
include ':ui-benchmarks'
include ':ui-samples'
